spring.application.name=Hotel-Reservation
spring.datasource.url=jdbc:mysql://localhost:3306/hoteldb
spring.datasource.username=your_username
spring.datasource.password=your_passward

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=6542
